name: lonberegning_mobile
description: Mobilapp til lønberegning system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9

  # State management
  provider: ^6.1.1

  # Networking
  http: ^1.1.2
  dio: ^5.4.0

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Date/Time
  intl: ^0.18.1

  # Navigation
  go_router: ^13.0.0

  # Location/GPS
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Notifications
  flutter_local_notifications: ^16.1.0
  workmanager: ^0.5.1

  # Security
  local_auth: ^2.1.7

  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  #   - icons/
